import Link from 'next/link';
import { Metadata } from 'next';
import styles from './layout.module.css';
import './globals.css';

export const metadata: Metadata = {
  title: `PoPo's Blog`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head />
      <body>
        <div className="app flex flex-col h-screen w-screen px-20">
          <header className='p-5 text-2xl font-extrabold basis-[10%] bg-slate-400 flex items-center justify-between'>
            <h1>PoPo&apos;s Blog</h1>
            <nav>
              <Link className='text-sm ml-2 font-semibold' href='/'>home</Link>
              <Link className='text-sm ml-2 font-semibold' href='/about'>about</Link>
              <Link className='text-sm ml-2 font-semibold' href='/contact'>posts</Link>
              <Link className='text-sm ml-2 font-semibold' href='/products'>contact</Link>
            </nav>
          </header>
          <main className='bg-slate-600 basis-[90%]'>
            {children}
          </main>
          <footer className='text-white flex items-center justify-center basis-[5%] bg-slate-800 text-center'>@all rights reserved by popo</footer>
        </div>
      </body>
    </html>
  )
}
