import './globals.css'
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head />
      <body>
        <header>
          <h1>Demo Note</h1>
          <nav>
            <Link href='/about'>About</Link>
            <Link href='/contact'>Contact</Link>
            <Link href='/product'>Products</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
