import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head />
      <body>
        <header>
          <h1>Demo Note</h1>
          <nav>
            <a>Contact</a>
            <a>About</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
